### ISSUE TITLE
cannot load such file -- cita-sdk-ruby (LoadError)

### ISSUE THREAD

**Issue by clearloop** [cryptape/cita-sdk-ruby#27]
It might be a stupid error, but I still can't solve it after whole night surfing on the stackoverflow...

```
Traceback (most recent call last):
	2: from rpc.rb:1:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cita-sdk-ruby (LoadError)
```

I tried to write code in `cita-sdk-ruby`'s path, it works, but I can't load it outside the path.

Though `gem info` can print cita-sdk-ruby's info, other gems work well while I requiring them.
```
*** LOCAL GEMS ***

cita-sdk-ruby (0.21.0, 0.20.0)
    Author: classicalliu
    Homepage: https://github.com/cryptape/cita-sdk-ruby
    License: MIT
    Installed at (0.21.0): /Users/mercury/Library/gems
                 (0.20.0): /Users/mercury/Library/gems

    Ruby CITA SDK
```

Here is my `gem environment`:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.2 (2019-03-13 patchlevel 47) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/clearloop/Library/gems
  - USER INSTALLATION DIRECTORY: /Users/clearloop/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/clearloop/Library/gems/bin
  - SPEC CACHE DIRECTORY: /Users/clearloop/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.6.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/mercury/Library/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://gems.ruby-china.com"]
```

And I've tried installing `cita-sdk-ruby` with `--user-install` tag.

**Comment by classicalliu** [comment]
What's mean of `load it outside the path`

**Comment by clearloop** [comment]
This works
```
# $HOME/Library/gems/cita-sdk-ruby-0.21.0/lib/test.rb
require 'cita';
```

This does not
```
# $HOME/tmp
```

**Comment by classicalliu** [comment]
Try to `require 'cita'` instead of `require 'cita-sdk-ruby'`

**Comment by clearloop** [comment]
__What I can't do is :__
I can't `require 'cita-sdk-ruby'` anywhere.

__What I can do is:__
> because my test file is just beside the `cita.rb`, the source file.

I can `require 'cita'` in: `$HOME/Library/gems/gems/cita-sdk-ruby-0.21.0/lib/test.rb`

__What happend:__
The source gem is okay, but I can't use it in a global path, neither `gem install cita-ruby-sdk` or configure it with `bundle`

**Comment by classicalliu** [comment]
> **What I can't do is :**
> I can't `require 'cita-sdk-ruby'` anywhere.
> 
> **What I can do is:**
> 
> > because my test file is just beside the `cita.rb`, the source file.
> 
> I can `require 'cita'` in: `$HOME/Library/gems/gems/cita-sdk-ruby-0.21.0/lib/test.rb`
> 
> **What happend:**
> The source gem is okay, but I can't use it in a global path, neither `gem install cita-ruby-sdk` nor configure it with `bundle`

`require 'cita` not `require 'cita-sdk-ruby'`, module file named `cita.rb`, so  use `require 'cita'`
In short, `require 'cita-sdk-ruby'` itself is a error

**Comment by clearloop** [comment]
yep, the problem is...I want to use `cita-sdk-ruby` in my ruby files.

The `require 'cita-sdk-ruby'` not work in my PC, it throw the error
```
 𝝺 pwd
/Users/clearloop/tmp
 𝝺 rb test.rb 
Traceback (most recent call last):
	2: from test.rb:1:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cita-ruby-sdk (LoadError)
 𝝺 
```
how can I reach it?

**Comment by classicalliu** [comment]
> yep, the problem is...I want to use `cita-sdk-ruby` in my ruby files.
> 
> The `require 'cita-sdk-ruby'` not work in my PC, it throw the error
> 
> ```
> require "cita-ruby-sdk"
> ```
> ```
>  𝝺 pwd
> /Users/clearloop/tmp
>  𝝺 rb test.rb 
> Traceback (most recent call last):
> 	2: from test.rb:1:in `<main>'
> 	1: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cita-ruby-sdk (LoadError)
>  𝝺 
> ```
> how can I reach it?

In any file, `require 'cita'` will get what you want ... the gem named `cita-sdk-ruby` but the module named `CITA`, use `require 'cita'` anywhere you want.
In short, every time you want to use `require 'cita-sdk-ruby'`, use `require 'cita'` instead.

**Comment by clearloop** [comment]
emmm, well, it works, I'm stupid totally...
